name: Debug CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Create Virtual Environment
      run: |
        python -m venv venv
        source venv/bin/activate
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r remoteMedi/requirements.txt
        pip install pytest-django
    - name: Run migrations
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python remoteMedi/manage.py migrate --settings=remoteMedi.settings.debug
    - name: Run tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: python remoteMedi/manage.py test remoteMedi/ --settings=remoteMedi.settings.debug

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Deploy to AWS
      env:
        VIRTUAL_ENV: ../venv
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
      working-directory: ./remoteMedi/
      run: zappa update dev
